"use client";

import React, { useEffect, useState } from "react";
import { cn } from "@/lib/utils"; // Optional utility

interface LoadingTextProps {
  isConnected?: boolean;
  notConnectedText?: string;
  isLoading: boolean;
  children?: React.ReactNode;
  className?: string;
}

export default function LoadingText({
  isConnected = true,
  notConnectedText = "Not Connected",
  isLoading,
  children,
  className
}: LoadingTextProps) {

  const [dots, setDots] = useState("");

  const textExpressions = [
    "Fetching Random Number",
    "Generating Game State",
    "Loading Game Data",
    "Preparing Game",
    "Connecting to the blockchain",
    "Waiting for ETH to hit $10,000",
    "Remember to tip your dealer",
    "Garga is the most handsome founder",
    "Rida is doing a free geez airdrop dm him for info",
    "Waiting for the blockchain to get off vacation",
    "Koko is in the Bahamas liquidity gone",
    "Calling Satoshi",
    "Call your mother",
    "Can dev do something?",
    "Verifying your vibes on-chain…",
    "Please hold, CZ is doing pushups",
    "Scanning your karma-to-wallet ratio",
    "Connecting to Elon’s Neuralink…",
    "Injecting hopium",
    "Downloading JPEGs to your retina",
    "Shuffling deck of degeneracy",
    "Waiting for Ethereum gas prices to calm down",
    "Pls no dump",
    "Praying to the memecoin gods",
    "We’re not stuck, you’re just impatient",
    "ApeCoin oracle is napping",
    "Staring at charts won’t help",
    "Your $ is safe-ish",
    "Loading faster than your airdrop",
    "Welcome anon, your sins are forgiven",
    "Someone poked the DAO again",
    "Realigning chakras with Solana downtime",
    "Vitalik is thinking…",
    "In a meeting with the SEC",
    "Spinning up a Lambo from the metaverse",
    "Oh no……….",
    "Waiting for your karma airdrop",
    "Retrieving funds from Mt. Gox",
    "Cross checking with your horoscopes",
    "Manifesting a green candle",
    "Who launched this contract?",
    "Disabling Ponzinomics module…",
    "Initiating copium protocol",
    "Burning your browser history",
    "Gordon winked market moving",
    "Loading… slower than Arbitrum governance",
    "One does not simply bridge from Base",
    "Your transaction is stuck in 2017",
    "You are the yield",
    "Listening to Machi’s mixtape",
    "Stealing alpha from group chats",
    "Vibe check: FAILED",
    "Syncing with the vibe layer",
    "Beep boop. Rida is a grouch",
    "This is definitely not financial advice",
    "Becoming a DAO just for fun",
    "Hashing your deepest regrets",
    "Waiting for someone to read the whitepaper",
    "Your coins are safe… we think",
    "We regret to inform you: you are the liquidity",
    "One more block… probably",
    "Pepe is watching",
    "Vitalik’s dog is reviewing your tx",
    "Processing your gm…",
    "Rugging in slow motion",
    "Gas fees sponsored by your ex",
    "Aligning with the moon’s gravitational pull",
    "Awaiting dev’s coffee to kick in",
    "Activating decentralization™",
    "Checking vibes… corrupted",
    "Please remain rugged at all times",
    "Staking your patience",
    "Waiting for bullish tweets",
    "Watching your bags with popcorn",
    "The real treasure was the ponzis we made along the way",
    "Trusting the code… yikes",
    "Touching grass… error",
    "Rebooting your luck",
    "Downloading your gambling sins to IPFS",
    "Confirming your net worth with ChatGPT",
    "Checking if you’re onchain enough",
    "Is this a DAO now?",
    "Remember: zero is just another support level",
    "Your future wife is watching this transaction",
    "Manifesting entry into THE group chat",
    "Awaiting your karma rebalance",
    "Simping for ETH gas refunds",
    "The vibes are immaculate, but slow",
    "Generating your exit liquidity",
    "Refreshing the memecoin meta",
    "You have been selected for an audit… JK",
    "Satoshi is online… just kidding",
    "Please tip your devs in memes",
    "Reading your portfolio's last rites",
    "Currently front-running you for fun",
    "HODLing this loading screen",
    "RugPull Detector: Calibrating…",
    "Your $APE is safe… unless",
    "Remember: it’s only a loss if you admit it",
    "Still more reliable than TradFi",
    "Gamblers Anonymous is 2 clicks away",
    "Recharging the banter engine",
    "Trust, bro",
    "Injecting some divine degen into your soul",
    "This screen is proof of work",
    "Your wallet smells like FOMO",
    "Your bags are heavy. Let’s go lighten them",
    "Loading your daily dose of delusion",
    "Burning gas like it’s daddy’s money",
    "We’re not late, we’re just vibing",
    "Bridging your soul to Layer 2",
    "Loading slower than your ROI",
    "Just a few more blocks, trust",
    "God left the group chat",
    "Downloading your gambling problem",
    "Memes are the only utility",
    "Checking if your ape is still alive",
    "Dev went to Burning Man again",
    "Resurrecting your exit liquidity",
    "You’re early… to the next rug",
    "Warming up the copium chamber",
    "Summoning the spirit of Doge",
    "Still better odds than Vegas",
    "One tx away from salvation",
    "Loading like a 2013 Bitcoin wallet",
    "Preparing your financial therapy session",
    "Please tip the priest in memecoins",
    "This casino accepts prayers and pain",
    "You pressed the wrong button again",
    "Staking your karma for penance",
    "Calling the liquidity hotline",
    "Unironically bullish on your L",
    "Just sign the tx, it’s fine",
    "Someone accidentally launched a DAO",
    "Devs are speedrunning bugs",
    "This isn’t DeFi, it’s DegenFi",
    "Adding more alpha to your illusion",
    "Trust the process (lol)",
    "We're working on it — kinda",
    "WAGMI (we all gamble miserably inside)",
    "Your wallet cries at night",
    "Still waiting on your vibe vesting",
    "We saw your wallet and said “oof”",
    "Burning through logic at L2 speed",
    "All sins welcome here",
    "Meme fast, pray hard",
    "This screen is proof of cope",
    "Do not resuscitate your bags",
    "Waiting for your bags to go to Valhalla",
    "Plz stop refreshing, you’ll break it more",
    "Your airdrop got stolen by monkeys",
    "On hold while CZ takes a nap",
    "We're checking if your luck's on-chain",
    "No insurance, only vibes",
    "Not a bug, it’s a divine feature",
    "Uploading your regrets to Arweave",
    "This is your sign to not YOLO",
    "Red candles, white knuckles",
    "Vitalik’s on a vision quest",
    "Sharding your hope into fragments",
    "Holy latency, Batman",
    "Waiting for your W to mint itself",
    "Searching for meaning in memecoins",
    "SBF is definitely not here",
    "Praying for your seed phrase",
    "Your meme karma is insufficient",
    "Just like your wallet balance",
    "Funding your next delusion",
    "We checked....you’re not early",
    "Too based to fail",
    "Installing dopamine drip...",
    "Your TX is still loading, like your potential",
    "Degen priest is in session",
    "Transaction confirmed... psych",
    "We sacrificed a goat for gas fees",
    "Unwrapping your financial trauma",
    "Still safer than Celsius",
    "One prayer = one confirmation",
    "Loading your favorite ponzi...",
    "You made it to the holy loading screen",
    "Ascend or rug, no in between",
    "Your gambling sins are on-chain forever",
    "We hope you're using a burner wallet",
    "Degen mode activated",
    "Still syncing with the Church of Risk",
    "This screen is more stable than your bags",
    "Verifying vibes and vibes only",
    "Your mom warned you about this",
    "This is why we can't have nice protocols",
    "Thou shalt not fade the meme",
    "Washing away your sins with liquidity",
    "Just hold, anon. Just hold.",
    "Moon? Nah, we're going to church",
    "Confirming your last 100 Ls",
    "Crossing fingers and bridging assets",
    "Waiting on divine intervention (and confirmations)",
    "Fetching some hopium from cold storage",
    "Updating your meme alignment",
    "You may now enter the ApeChurch confessional",
    "We read your bags and started fasting",
    "Still less volatile than your ex",
    "Processing your membership in the Degen Cult",
    "Trustless? More like helpless.",
    "Burnt offerings accepted in $APE",
    "Enlightenment pending…",
    "Your PnL is none of our business (but we judged it)",
    "Summoning more exit liquidity",
    "We speak in tongues and memes",
    "He who believes in the pump shall be rewarded",
    "Still loading because we’re underfunded",
    "All hail the block delay",
    "Apes don’t do patience",
    "Praise be to the chain",
    "And on the 8th day, God deployed ApeChurch",
    "Sacrificing a goblin for more blockspace…",
    "Yo Cam, can I borrow 1M $APE real quick?",
    "Garga will be building Otherside in the afterlife.",
    "Solana is more than just a shitcoin chain… allegedly.",
    "Send me 200 $APE, I’ll send you 400 back.",
    "The house always wins. Except when it doesn’t. But mostly it does.",
    "Loading… unlike ETH transactions during peak hours.",
    "Your transaction is cooking harder than Solana in 2021.",
    "Don’t worry, your $APE is SAFU-ish.",
    "One sec, asking Gordon for approval…",
    "Please hold while Yuga debates IP rights.",
    "Our devs are working harder than BAYC floor traders.",
    "Reloading because your luck was too degen.",
    "Ape Church welcomes all sinners and degeners.",
    "Just bridging your brain to ApeChain…",
    "Almost ready — unlike The Otherside.",
    "Someone just hit a 69x and crashed the vibes.",
    "Praying for your bankroll, champ.",
    "Your $APE is stretching before the deity of RNG.",
    "The Cult approves this loading screen.",
    "Wen Lambo? Wen wife back?",
    "Someone’s uncle just bought the top.",
    "Summoning the spirit of Fidenza #1…",
    "One sec, gas fees arguing with destiny.",
    "You’re loading faster than Binance listings.",
    "Yuga lore intensifying…",
    "Loading your luck… please be patient, unlike crypto Twitter.",
    "Someone is fighting in the Discord again.",
    "More liquidity arriving than at a Solana presale.",
    "Hold on — ApeChain is gossiping.",
    "If this loads, you owe the house a banana.",
    "Your destiny is being calculated on-chain.",
    "If this fails, blame the devs.",
    "Your $APE is knocking on heaven’s vault.",
    "Don’t close the app — we saw what you did last time.",
    "Loading… but in a bullish way.",
    "This screen loads faster than BAYC floor drops.",
    "RNG gods are deciding whether you eat or cry.",
    "Almost there — slower than Yuga announcements.",
    "Someone just bridged $SHIB to ApeChain accidentally.",
    "Relax, your funds aren’t going anywhere. Maybe.",
    "The house is whispering sweet yields to your wallet.",
    "Loading your next questionable life choice.",
    "Ape Church forgives all except paper hands.",
    "High volatility detected in your aura.",
    "Don’t worry, your $APE is in cold storage… somewhere.",
    "Updating your win rate. It’s still bad.",
    "Bro your luck is on L2.",
    "Loading faster than your ex moves on.",
    "Praying for your solvency.",
    "Data incoming: 90% chance you degen again.",
    "Ape Church has logged your sins.",
    "RNG is watching you.",
    "You better hope Cam doesn’t charge interest.",
    "Garga fingerprints detected on this loading screen.",
    "Loading… powered by hopium.",
    "Your wallet is sweating.",
    "One sec, telling your mom you’re still employed.",
    "The banana oracle is reviewing your fate.",
    "Don’t rage quit — the house likes that.",
    "If you lose, say it was “for research.”",
    "Uploading your degen soul to the blockchain.",
    "Wen $APE stimulus? Asking for a friend.",
    "Loading… because Yuga said so.",
    "Are you even ready for this multiplier?",
    "Summoning Pyth RNG — please clap.",
    "Your luck is syncing with ApeChain validators.",
    "Nice.",
    "404: Responsible gambling not found.",
    "The cult sees everything.",
    "Someone just tried bridging Monopoly money.",
    "You’re approved for degen activity.",
    "Your $APE is now 90% hopium.",
    "If this takes too long, blame Solana outages.",
    "The priest of volatility is preparing your fate.",
    "We’re verifying if you’re truly worthy of a win.",
    "Loading… do not throw banana at the screen.",
    "A small crab is currently carrying your transaction.",
    "Maximizing your chances of complaining on Twitter.",
    "One sec — someone rage bet the treasury.",
    "Charging your luck meter… still empty.",
    "If this loads, you’re officially a degen.",
    "Your wallet is negotiating with destiny.",
    "Welcome back, sinner.",
    "Ape Church is adjusting your vibe score.",
    "The house is sharpening its edge.",
    "Your bankroll is shaking violently.",
    "Bless this spin, for it may be your last.",
    "Organizing your losses alphabetically.",
    "Preparing your next “just one more” moment.",
    "Decoding your questionable spending habits.",
    "Someone just hit 420x and ruined the curve.",
    "Pushing your luck to mainnet.",
    "Building suspense like Yuga announcements.",
    "Confirming your TVL in bad decisions.",
    "Loading… powered by caffeinated devs.",
    "All wins are final, all losses are your fault.",
    "Retrieving your previous sins from cold storage.",
    "Luck.exe is booting… good luck.",
    "You’re early. Or late. No one knows.",
    "Your $APE is watching you gamble.",
    "The house likes your confidence. Delicious.",
    "No refunds. This isn’t Coinbase.",
    "Monk mode activated — pray harder.",
    "Loading faster than Yuga lawsuits.",
    "Preparing your next bad beat tweet.",
    "Please wait — your degen upgrade is downloading.",
    "Someone just asked when Otherside is launching again.",
    "Tripsters would’ve never let this happen.",
    "Loading… don’t blame Kyle.",
    "Touch grass? No. Touch $APE.",
    "Calculating how screwed you might be.",
    "The Church accepts all offerings… especially yours.",
    "The blockchain remembers everything.",
    "Don’t lie — you deposited more than you meant to.",
    "Ape Church doesn’t do customer support for bad luck.",
    "One sec — feeding the validators bananas.",
    "If this crashes, it’s bullish.",
    "Accepting prayers, ignoring excuses.",
    "The cult salutes your degeneracy.",
    "We told your wallet to behave. It refused.",
    "Opening the gates of volatility.",
    "Loading your next sermon of pain.",
    "Your luck is about to get rugged.",
    "Hold on — someone is minting something dumb.",
    "We’re checking if you’re really that lucky.",
    "Someone just typed “wen airdrop” again.",
    "Your fortune is being audited.",
    "Please wait — organized chaos in progress.",
    "Loading… like a Binance user in 2017.",
    "Detected: high conviction, low balance.",
    "The house is licking its lips.",
    "Don’t worry — it only hurts the first time.",
    "You’re one win away from tweeting a manifesto.",
    "Ape Church loading… saints cry, degens smile.",
    "Breathing life into your next gamble.",
    "99% skill, 1% luck. Or maybe the opposite.",
    "RNG says: try again, bro.",
    "Preparing your next hopium injection.",
    "Yuga lore buff applied.",
    "Your luck is being fine-tuned in the lab.",
    "One sec — the devs are arguing about naming conventions.",
    "Loading faster than APE during announcements.",
    "Keep calm — your wallet can’t hear you scream.",
    "This might take as long as ApeChain mainnet.",
    "Your sins are being validated on-chain.",
    "The priest says you need more $APE.",
    "The house whispers: “again.”",
    "RNG is flipping your destiny coin.",
    "151–200: PURE DEGEN SPIRIT",
    "Your luck is coping in real time.",
    "Calculating risk level: idiot.",
    "Welcome back, son. The cult missed you.",
    "Your bankroll is trembling.",
    "This load screen is your last moment of peace.",
    "One sec — we’re rug-checking your aura.",
    "You’re betting like someone who owes Cam money.",
    "Loading up your favorite bad habit.",
    "Preparing you for another questionable decision.",
    "Ape Church does not bless paper hands.",
    "Your fate is being written by a banana-powered oracle.",
    "Congrats, you’re now 86% degen.",
    "Someone just hit a 2x and acted like it was a 200x.",
    "Loading… because you wouldn’t stop clicking.",
    "Don’t worry — everyone loses here equally.",
    "RNG is flipping you off politely.",
    "Your luck is still stuck in cross-chain transit.",
    "One sec — approving your next mistake.",
    "Waiting for your wallet to admit its issues.",
    "Ape Church detects you’re chasing losses.",
    "You look like you need a stimmy.",
    "Your balance is about to go on a journey.",
    "We’re checking if you’re smart enough to stop. (You’re not.)",
    "Someone just yelled “ALL IN” again.",
    "Loading… your bankroll’s obituary.",
    "Updating your rank in the Cult of Chaos.",
    "This may take a moment — your luck is outdated.",
    "Your $APE is doing warmups.",
    "Someone tried paying gas in Dogecoin.",
    "Loading your upgrade to full degen form.",
    "The house is shining its edge.",
    "Your luck is being drawn by a drunk pixel artist.",
    "RNG: “lol good luck buddy.”",
    "Your next win is hidden behind 17 losses.",
    "We’re tightening your seatbelt for volatility.",
    "Your coping level is off the charts.",
    "This load screen has more utility than half of crypto.",
    "Your destiny has been outsourced to Pyth.",
    "The cult demands more deposits.",
    "Hold on — your luck is rebooting.",
    "Someone just listed their ape for 12 ETH by accident.",
    "Ape Church doesn’t judge… out loud.",
    "Blessings upon your bankroll. It needs it.",
    "Summoning the spirit of BAYC #1.",
    "Ape Church loading… repent your leverage.",
    "You look like you chase green candles.",
    "The next click decides your whole personality.",
    "Good luck, champ. You’ll need it.",
    "This is where winners are born and losers cope.",
    "Loading complete — welcome back, degen."
  ]

  const [expression, setExpression] = useState(textExpressions[Math.floor(Math.random() * textExpressions.length)]);

  useEffect(() => {
    if (!isLoading) return;

    const interval = setInterval(() => {
      setExpression(textExpressions[Math.floor(Math.random() * textExpressions.length)]);
    }, 1900);

    return () => clearInterval(interval);
  }, [isLoading]);

  useEffect(() => {
    if (!isLoading) return;

    const interval = setInterval(() => {
      setDots((prev) => (prev.length >= 3 ? "" : prev + "."));
    }, 500);

    return () => clearInterval(interval);
  }, [isLoading]);

  if (!isConnected) {
    return (
      <p
        className={cn(
          "text-base font-semibold text-muted-foreground",
          className
        )}
      >
        {notConnectedText}
      </p>
    );
  }

  return isLoading ? (
    <p
      className={cn("text-base font-semibold text-muted-foreground", className)}
    >
      {expression}
      <span className="inline-block w-[1ch]">{dots}</span>
    </p>
  ) : (
    <p className={cn(className)}>{children}</p>
  );
}
